# Generated by Django 5.1.7 on 2025-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petpals", "0002_alter_userprofile_picture_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                upload_to="profile_images",
            ),
        ),
    ]
