# Generated by Django 5.1.7 on 2025-03-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petpals", "0002_alter_userprofile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
